// <auto-generated />
using System;
using AppParquadero.Infraestructura.Datos.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppParqueadero.Infraestructura.Datos.Migrations
{
    [DbContext(typeof(ParqueaderoContexto))]
    [Migration("20221118214918_primermigracionV.1")]
    partial class primermigracionV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("AppParqueadero.Dominio.Cliente", b =>
                {
                    b.Property<Guid>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TipoDocumuento")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("usuarioCrea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Empleado", b =>
                {
                    b.Property<Guid>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TipoDocumuento")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("usuarioCrea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoId");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Horario", b =>
                {
                    b.Property<Guid>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioCrea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HorarioId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Tarifa", b =>
                {
                    b.Property<Guid>("TarifaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("usuarioCrea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TarifaId");

                    b.ToTable("Tarifa");

                    b.HasData(
                        new
                        {
                            TarifaId = new Guid("7f609f85-596b-4a1e-9776-2acedf942319"),
                            Tipo = "Auto",
                            Valor = 3000m
                        },
                        new
                        {
                            TarifaId = new Guid("9d5ce7e2-678c-43a5-a6ea-df7a2d4c47ee"),
                            Tipo = "Moto",
                            Valor = 1000m
                        });
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Ticket", b =>
                {
                    b.Property<Guid>("TickedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraDeEntrada")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("HoraDeSalida")
                        .HasColumnType("DateTime");

                    b.Property<Guid>("PuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TarifaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Total")
                        .HasColumnType("Decimal");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("usuarioCrea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TickedId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("TarifaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Ticked");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioCrea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Puesto", b =>
                {
                    b.Property<Guid>("PuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CodigoPuesto")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Disponibilidad")
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime?>("FechaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("usuarioCrea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuarioModifica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PuestoId");

                    b.ToTable("Puesto");

                    b.HasData(
                        new
                        {
                            PuestoId = new Guid("2b4a2de9-1596-4c53-beea-418a26d44bac"),
                            CodigoPuesto = "A0",
                            Disponibilidad = "Disponible"
                        },
                        new
                        {
                            PuestoId = new Guid("60bd82ff-b63d-4649-b620-f6333de4dafb"),
                            CodigoPuesto = "A1",
                            Disponibilidad = "Disponible"
                        },
                        new
                        {
                            PuestoId = new Guid("bab08f42-2fa8-430b-88d5-6ec72c917f27"),
                            CodigoPuesto = "A2",
                            Disponibilidad = "Disponible"
                        },
                        new
                        {
                            PuestoId = new Guid("17d29544-23c1-4dcd-97f3-3dbc1ca31885"),
                            CodigoPuesto = "A3",
                            Disponibilidad = "Disponible"
                        },
                        new
                        {
                            PuestoId = new Guid("803e074a-6484-4275-8e48-f50210a1ba38"),
                            CodigoPuesto = "A4",
                            Disponibilidad = "Disponible"
                        },
                        new
                        {
                            PuestoId = new Guid("4c76be66-0fc0-4646-a599-019f44c24608"),
                            CodigoPuesto = "A5",
                            Disponibilidad = "Disponible"
                        },
                        new
                        {
                            PuestoId = new Guid("65a344c7-9cc5-4e6b-9e74-bc0187ed81e9"),
                            CodigoPuesto = "A6",
                            Disponibilidad = "Disponible"
                        },
                        new
                        {
                            PuestoId = new Guid("f3ba6f58-c4bf-45d5-8276-894bc29d2103"),
                            CodigoPuesto = "A7",
                            Disponibilidad = "Disponible"
                        },
                        new
                        {
                            PuestoId = new Guid("0b6ac818-00d8-45ad-bddc-cde7c02fadbb"),
                            CodigoPuesto = "A8",
                            Disponibilidad = "Disponible"
                        },
                        new
                        {
                            PuestoId = new Guid("249ee805-b75b-4f49-9eba-f6fee7628377"),
                            CodigoPuesto = "A9",
                            Disponibilidad = "Disponible"
                        });
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Reserva", b =>
                {
                    b.Property<Guid>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("DateTime");

                    b.Property<Guid>("PuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Vehiculo", b =>
                {
                    b.Property<Guid>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Placa")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(20)");

                    b.HasKey("VehiculoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Horario", b =>
                {
                    b.HasOne("AppParqueadero.Dominio.Entidades.Empleado", "Empleado")
                        .WithMany("Horarios")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Ticket", b =>
                {
                    b.HasOne("AppParqueadero.Dominio.Cliente", "Cliente")
                        .WithMany("Tickets")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParqueadero.Dominio.Entidades.Empleado", "Empleado")
                        .WithMany("Tickets")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParqueadero.Dominio.Puesto", "Puesto")
                        .WithMany("Tickets")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParqueadero.Dominio.Entidades.Tarifa", "Tarifa")
                        .WithMany("Tickets")
                        .HasForeignKey("TarifaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParqueadero.Dominio.Vehiculo", "Vehiculo")
                        .WithMany("Tickets")
                        .HasForeignKey("VehiculoId")
                        .HasConstraintName("Fk_Vehiculo_VehiculoID")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Puesto");

                    b.Navigation("Tarifa");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("AppParqueadero.Dominio.Entidades.Empleado", "Empleado")
                        .WithOne("Usuario")
                        .HasForeignKey("AppParqueadero.Dominio.Entidades.Usuario", "EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Reserva", b =>
                {
                    b.HasOne("AppParqueadero.Dominio.Cliente", "cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParqueadero.Dominio.Puesto", "Puesto")
                        .WithMany("Reservas")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppParqueadero.Dominio.Vehiculo", "Vehiculo")
                        .WithMany("Reservas")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("Puesto");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Vehiculo", b =>
                {
                    b.HasOne("AppParqueadero.Dominio.Cliente", "cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Cliente", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Tickets");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Empleado", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Tickets");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Entidades.Tarifa", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Puesto", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AppParqueadero.Dominio.Vehiculo", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
